[2024-08-13T01:58:49.277+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_heart_data.obtain_original_data manual__2024-08-13T01:58:49.088597+00:00 [queued]>
[2024-08-13T01:58:49.282+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_heart_data.obtain_original_data manual__2024-08-13T01:58:49.088597+00:00 [queued]>
[2024-08-13T01:58:49.283+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-08-13T01:58:49.290+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): obtain_original_data> on 2024-08-13 01:58:49.088597+00:00
[2024-08-13T01:58:49.292+0000] {standard_task_runner.py:60} INFO - Started process 1123 to run task
[2024-08-13T01:58:49.294+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_heart_data', 'obtain_original_data', 'manual__2024-08-13T01:58:49.088597+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmp7m4gjtaw']
[2024-08-13T01:58:49.296+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask obtain_original_data
[2024-08-13T01:58:49.325+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_heart_data.obtain_original_data manual__2024-08-13T01:58:49.088597+00:00 [running]> on host 9c98cbfa0d20
[2024-08-13T01:58:49.366+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Facundo Adrian Lucianna' AIRFLOW_CTX_DAG_ID='process_etl_heart_data' AIRFLOW_CTX_TASK_ID='obtain_original_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-13T01:58:49.088597+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-13T01:58:49.088597+00:00'
[2024-08-13T01:58:49.367+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvaah65gl0 --system-site-packages --python=python
[2024-08-13T01:58:49.370+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T01:58:49.749+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 184ms
[2024-08-13T01:58:49.749+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvaah65gl0, clear=False, no_vcs_ignore=False, global=True)
[2024-08-13T01:58:49.749+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpnyxdtrxz)
[2024-08-13T01:58:49.749+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-08-13T01:58:49.750+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-08-13T01:58:49.766+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvaah65gl0/bin/pip install -r /tmp/venvaah65gl0/requirements.txt
[2024-08-13T01:58:49.769+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T01:58:50.144+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2024-08-13T01:58:50.481+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvaah65gl0/requirements.txt (line 1))
[2024-08-13T01:58:50.562+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-08-13T01:58:50.727+0000] {process_utils.py:190} INFO - Collecting ucimlrepo==0.0.3 (from -r /tmp/venvaah65gl0/requirements.txt (line 2))
[2024-08-13T01:58:50.740+0000] {process_utils.py:190} INFO -   Downloading ucimlrepo-0.0.3-py3-none-any.whl.metadata (5.2 kB)
[2024-08-13T01:58:50.771+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (1.34.158)
[2024-08-13T01:58:50.772+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (1.34.158)
[2024-08-13T01:58:50.773+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (1.24.4)
[2024-08-13T01:58:50.773+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (23.2)
[2024-08-13T01:58:50.774+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (2.0.3)
[2024-08-13T01:58:50.774+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (14.0.2)
[2024-08-13T01:58:50.775+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (4.12.2)
[2024-08-13T01:58:50.778+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (0.10.0)
[2024-08-13T01:58:50.779+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (0.10.2)
[2024-08-13T01:58:50.782+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (2.8.2)
[2024-08-13T01:58:50.783+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (1.26.18)
[2024-08-13T01:58:50.821+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (2023.3.post1)
[2024-08-13T01:58:50.821+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (2023.4)
[2024-08-13T01:58:50.824+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvaah65gl0/requirements.txt (line 1)) (1.16.0)
[2024-08-13T01:58:50.847+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-08-13T01:58:50.880+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.8/403.8 kB 12.9 MB/s eta 0:00:00
[2024-08-13T01:58:50.888+0000] {process_utils.py:190} INFO - Downloading ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
[2024-08-13T01:58:52.064+0000] {process_utils.py:190} INFO - Installing collected packages: ucimlrepo, awswrangler
[2024-08-13T01:58:52.166+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0 ucimlrepo-0.0.3
[2024-08-13T01:58:52.233+0000] {process_utils.py:190} INFO - 
[2024-08-13T01:58:52.234+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.2
[2024-08-13T01:58:52.234+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-08-13T01:58:52.299+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvaah65gl0/bin/python /tmp/venv-callia6fendi/script.py /tmp/venv-callia6fendi/script.in /tmp/venv-callia6fendi/script.out /tmp/venv-callia6fendi/string_args.txt /tmp/venv-callia6fendi/termination.log
[2024-08-13T01:58:52.300+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T01:58:55.109+0000] {process_utils.py:190} INFO - [[34m2024-08-13T01:58:55.109+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T01:58:55.151+0000] {process_utils.py:190} INFO - [[34m2024-08-13T01:58:55.151+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T01:58:55.275+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-13T01:58:55.280+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_heart_data, task_id=obtain_original_data, execution_date=20240813T015849, start_date=20240813T015849, end_date=20240813T015855
[2024-08-13T01:58:55.307+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-13T01:58:55.319+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
