[2024-08-13T02:58:47.987+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_heart_data.split_dataset scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-13T02:58:47.990+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_heart_data.split_dataset scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-13T02:58:47.990+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-08-13T02:58:47.995+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): split_dataset> on 2024-08-12 00:00:00+00:00
[2024-08-13T02:58:47.997+0000] {standard_task_runner.py:60} INFO - Started process 657 to run task
[2024-08-13T02:58:47.998+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_heart_data', 'split_dataset', 'scheduled__2024-08-12T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmp2533hz5p']
[2024-08-13T02:58:47.999+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask split_dataset
[2024-08-13T02:58:48.018+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_heart_data.split_dataset scheduled__2024-08-12T00:00:00+00:00 [running]> on host 47ccda1db683
[2024-08-13T02:58:48.044+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Facundo Adrian Lucianna' AIRFLOW_CTX_DAG_ID='process_etl_heart_data' AIRFLOW_CTX_TASK_ID='split_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-12T00:00:00+00:00'
[2024-08-13T02:58:48.045+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvoj0digio --system-site-packages --python=python
[2024-08-13T02:58:48.047+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T02:58:48.328+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 124ms
[2024-08-13T02:58:48.328+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvoj0digio, clear=False, no_vcs_ignore=False, global=True)
[2024-08-13T02:58:48.328+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpvwek0dlw)
[2024-08-13T02:58:48.329+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-08-13T02:58:48.329+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-08-13T02:58:48.343+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvoj0digio/bin/pip install -r /tmp/venvoj0digio/requirements.txt
[2024-08-13T02:58:48.346+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T02:58:48.717+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2024-08-13T02:58:48.862+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvoj0digio/requirements.txt (line 1))
[2024-08-13T02:58:48.909+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-08-13T02:58:48.914+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvoj0digio/requirements.txt (line 2)) (1.3.2)
[2024-08-13T02:58:48.932+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (1.34.158)
[2024-08-13T02:58:48.933+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (1.34.158)
[2024-08-13T02:58:48.933+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (1.24.4)
[2024-08-13T02:58:48.934+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (23.2)
[2024-08-13T02:58:48.934+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (2.0.3)
[2024-08-13T02:58:48.935+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (14.0.2)
[2024-08-13T02:58:48.935+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (4.12.2)
[2024-08-13T02:58:48.948+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy>=1.5.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvoj0digio/requirements.txt (line 2)) (1.10.1)
[2024-08-13T02:58:48.949+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvoj0digio/requirements.txt (line 2)) (1.4.2)
[2024-08-13T02:58:48.949+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvoj0digio/requirements.txt (line 2)) (3.5.0)
[2024-08-13T02:58:48.951+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (0.10.0)
[2024-08-13T02:58:48.951+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (0.10.2)
[2024-08-13T02:58:48.954+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (2.8.2)
[2024-08-13T02:58:48.955+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (1.26.18)
[2024-08-13T02:58:48.989+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (2023.3.post1)
[2024-08-13T02:58:48.989+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (2023.4)
[2024-08-13T02:58:49.002+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvoj0digio/requirements.txt (line 1)) (1.16.0)
[2024-08-13T02:58:49.026+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-08-13T02:58:49.052+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.8/403.8 kB 16.6 MB/s eta 0:00:00
[2024-08-13T02:58:50.197+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2024-08-13T02:58:50.303+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0
[2024-08-13T02:58:50.378+0000] {process_utils.py:190} INFO - 
[2024-08-13T02:58:50.379+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.2
[2024-08-13T02:58:50.379+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-08-13T02:58:50.432+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvoj0digio/bin/python /tmp/venv-callc2dsdv9r/script.py /tmp/venv-callc2dsdv9r/script.in /tmp/venv-callc2dsdv9r/script.out /tmp/venv-callc2dsdv9r/string_args.txt /tmp/venv-callc2dsdv9r/termination.log
[2024-08-13T02:58:50.435+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T02:58:51.413+0000] {process_utils.py:190} INFO - [[34m2024-08-13T02:58:51.413+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T02:58:51.478+0000] {process_utils.py:190} INFO - [[34m2024-08-13T02:58:51.478+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T02:58:51.502+0000] {process_utils.py:190} INFO - [[34m2024-08-13T02:58:51.502+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T02:58:51.527+0000] {process_utils.py:190} INFO - [[34m2024-08-13T02:58:51.527+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T02:58:51.538+0000] {process_utils.py:190} INFO - [[34m2024-08-13T02:58:51.538+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T02:58:51.565+0000] {process_utils.py:190} INFO - [[34m2024-08-13T02:58:51.565+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T02:58:51.575+0000] {process_utils.py:190} INFO - [[34m2024-08-13T02:58:51.575+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T02:58:51.600+0000] {process_utils.py:190} INFO - [[34m2024-08-13T02:58:51.600+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T02:58:51.610+0000] {process_utils.py:190} INFO - [[34m2024-08-13T02:58:51.610+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T02:58:51.687+0000] {process_utils.py:190} INFO - [[34m2024-08-13T02:58:51.686+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T02:58:51.836+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-13T02:58:51.842+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_heart_data, task_id=split_dataset, execution_date=20240812T000000, start_date=20240813T025847, end_date=20240813T025851
[2024-08-13T02:58:51.861+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-13T02:58:51.870+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-13T23:06:46.443+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_heart_data.split_dataset scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-13T23:06:46.446+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_heart_data.split_dataset scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-13T23:06:46.446+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-08-13T23:06:46.451+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): split_dataset> on 2024-08-12 00:00:00+00:00
[2024-08-13T23:06:46.453+0000] {standard_task_runner.py:60} INFO - Started process 769 to run task
[2024-08-13T23:06:46.455+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_heart_data', 'split_dataset', 'scheduled__2024-08-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmp55a3rd3z']
[2024-08-13T23:06:46.456+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask split_dataset
[2024-08-13T23:06:46.475+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_heart_data.split_dataset scheduled__2024-08-12T00:00:00+00:00 [running]> on host 724c87fe0c82
[2024-08-13T23:06:46.505+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Facundo Adrian Lucianna' AIRFLOW_CTX_DAG_ID='process_etl_heart_data' AIRFLOW_CTX_TASK_ID='split_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-12T00:00:00+00:00'
[2024-08-13T23:06:46.506+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvkddfrwv_ --system-site-packages --python=python
[2024-08-13T23:06:46.508+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T23:06:46.741+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 74ms
[2024-08-13T23:06:46.742+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvkddfrwv_, clear=False, no_vcs_ignore=False, global=True)
[2024-08-13T23:06:46.742+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-08-13T23:06:46.742+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-08-13T23:06:46.742+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-08-13T23:06:46.758+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvkddfrwv_/bin/pip install -r /tmp/venvkddfrwv_/requirements.txt
[2024-08-13T23:06:46.760+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T23:06:47.270+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.6.0 (from -r /tmp/venvkddfrwv_/requirements.txt (line 1))
[2024-08-13T23:06:47.271+0000] {process_utils.py:190} INFO -   Using cached awswrangler-3.6.0-py3-none-any.whl.metadata (23 kB)
[2024-08-13T23:06:47.272+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvkddfrwv_/requirements.txt (line 2)) (1.3.2)
[2024-08-13T23:06:47.290+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (1.34.158)
[2024-08-13T23:06:47.290+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (1.34.158)
[2024-08-13T23:06:47.291+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (1.24.4)
[2024-08-13T23:06:47.291+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (23.2)
[2024-08-13T23:06:47.292+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (2.0.3)
[2024-08-13T23:06:47.292+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=7.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (14.0.2)
[2024-08-13T23:06:47.292+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (4.12.2)
[2024-08-13T23:06:47.306+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy>=1.5.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvkddfrwv_/requirements.txt (line 2)) (1.10.1)
[2024-08-13T23:06:47.307+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvkddfrwv_/requirements.txt (line 2)) (1.4.2)
[2024-08-13T23:06:47.307+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvkddfrwv_/requirements.txt (line 2)) (3.5.0)
[2024-08-13T23:06:47.309+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (0.10.0)
[2024-08-13T23:06:47.309+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (0.10.2)
[2024-08-13T23:06:47.312+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (2.8.2)
[2024-08-13T23:06:47.313+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (1.26.18)
[2024-08-13T23:06:47.348+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (2023.3.post1)
[2024-08-13T23:06:47.348+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (2023.4)
[2024-08-13T23:06:47.361+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.6.0->-r /tmp/venvkddfrwv_/requirements.txt (line 1)) (1.16.0)
[2024-08-13T23:06:47.374+0000] {process_utils.py:190} INFO - Using cached awswrangler-3.6.0-py3-none-any.whl (403 kB)
[2024-08-13T23:06:48.570+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2024-08-13T23:06:48.680+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.6.0
[2024-08-13T23:06:48.745+0000] {process_utils.py:190} INFO - 
[2024-08-13T23:06:48.746+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.2
[2024-08-13T23:06:48.746+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-08-13T23:06:48.805+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvkddfrwv_/bin/python /tmp/venv-call01ly56nm/script.py /tmp/venv-call01ly56nm/script.in /tmp/venv-call01ly56nm/script.out /tmp/venv-call01ly56nm/string_args.txt /tmp/venv-call01ly56nm/termination.log
[2024-08-13T23:06:48.807+0000] {process_utils.py:186} INFO - Output:
[2024-08-13T23:06:49.752+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:49.752+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T23:06:49.809+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:49.809+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T23:06:49.834+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:49.833+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T23:06:49.857+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:49.857+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T23:06:49.868+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:49.868+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T23:06:49.892+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:49.891+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T23:06:49.901+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:49.901+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T23:06:49.924+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:49.924+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T23:06:49.933+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:49.933+0000[0m] {[34mcredentials.py:[0m1147} INFO[0m - Found credentials in environment variables.[0m
[2024-08-13T23:06:50.007+0000] {process_utils.py:190} INFO - [[34m2024-08-13T23:06:50.007+0000[0m] {[34mconfigprovider.py:[0m952} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2024-08-13T23:06:50.143+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-13T23:06:50.149+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_heart_data, task_id=split_dataset, execution_date=20240812T000000, start_date=20240813T230646, end_date=20240813T230650
[2024-08-13T23:06:50.196+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-13T23:06:50.206+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
